name: 打包vue项目

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: 打包vue项目
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      # 生成changelog
      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 打包
        run: npm run build

      - name: vue项目发布到github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true # 清理目标分支上的旧文件
          # clean-exclude: |
          #   .gitignore
          #   README.md
          # commit-message: "chore: 更新网站 [skip ci]"
          # token: ${{ secrets.GITHUB_TOKEN }}
          # force: true # 强制推送到目标分支
